CLASS zrap400_tc_travel_lcp_ssc_o2 DEFINITION  PUBLIC FINAL CREATE PUBLIC FOR TESTING.
  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.
CLASS zrap400_tc_travel_lcp_ssc_o2  IMPLEMENTATION.
ENDCLASS.
